### ISSUE TITLE
关于空行和回车的删除

### ISSUE THREAD

**Issue by zodiac911** [CyC2018/Text-Typesetting#1]
markdown 中的连续多空行确实没用，但是在一些情况下，回车的删除虽然不会影响实际的显示效果，但是却会影响 md 文件对人的可读性
比如
`
# 一级标题
## 二级标题
`
会被格式化为
`
# 一级标题 ## 二级标题
`
能不能提供一个接口 让用户进行选择

**Comment by CyC2018** [comment]
@zodiac911 你是说会出现下面这种转换吗？

```
# 一级标题
## 二级标题
```

```
# 一级标题## 二级标题
```

**Comment by CyC2018** [comment]
@zodiac911 这个问题我已经修复了
